"""add page customisation fields to orders

Revision ID: 693206dd750b
Revises: 0001_initial_schema
Create Date: 2026-05-14 20:34:02.263762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693206dd750b'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cover_subtitle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preface_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('closing_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('closing_message')
        batch_op.drop_column('preface_message')
        batch_op.drop_column('cover_subtitle')
        batch_op.drop_column('cover_title')

    # ### end Alembic commands ###
